# Generated by Django 5.2.8 on 2026-01-29 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mautamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_name', models.CharField(max_length=200)),
                ('passport', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Agent jiske liye ye mautamer hai', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mautamers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pax_name'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vNo', models.CharField(max_length=50, unique=True)),
                ('agentName', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('groupName', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_location', models.CharField(max_length=200)),
                ('type_of_transfer', models.CharField(blank=True, choices=[('bus', 'Bus'), ('car', 'Car'), ('van', 'Van'), ('taxi', 'Taxi'), ('other', 'Other')], default='', max_length=20)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportations', to='api.voucher')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_head', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('checking_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('nights', models.IntegerField(default=0)),
                ('hotel_name', models.CharField(max_length=200)),
                ('room_type', models.CharField(blank=True, choices=[('single', 'Single Room'), ('double', 'Double Room'), ('triple', 'Triple Room'), ('quad', 'Quad Room'), ('family', 'Family Room')], default='', max_length=20)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='api.voucher')),
            ],
            options={
                'ordering': ['checking_date'],
            },
        ),
        migrations.CreateModel(
            name='FlightInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('sector_from', models.CharField(blank=True, default='', max_length=100)),
                ('sector_to', models.CharField(blank=True, default='', max_length=100)),
                ('depart_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('departure_flight_no', models.CharField(blank=True, default='', max_length=50)),
                ('departure_flight', models.CharField(blank=True, default='', max_length=200)),
                ('departure_pnr', models.CharField(blank=True, default='', max_length=50)),
                ('nights', models.IntegerField(default=0, help_text='Departure - Arrival nights')),
                ('return_date', models.DateField()),
                ('return_time', models.TimeField()),
                ('return_flight_no', models.CharField(blank=True, default='', max_length=50)),
                ('return_flight', models.CharField(blank=True, default='', max_length=200)),
                ('return_sector_from', models.CharField(blank=True, default='', max_length=100)),
                ('return_sector_to', models.CharField(blank=True, default='', max_length=100)),
                ('return_pnr', models.CharField(blank=True, default='', max_length=50)),
                ('shirka', models.CharField(blank=True, default='', max_length=200)),
                ('iata', models.CharField(blank=True, default='', max_length=50)),
                ('service_no', models.CharField(blank=True, default='', max_length=50)),
                ('voucher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flight_info', to='api.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherMautamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mautamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_assignments', to='api.mautamer')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_mautamers', to='api.voucher')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('voucher', 'mautamer')},
            },
        ),
    ]
