# Generated by Django 5.2.8 on 2026-01-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mautamer_added_by_mautamer_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mautamer',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='mautamer',
            name='created_at',
        ),
    ]
